### ISSUE TITLE
Create logout button

### ISSUE THREAD

**Issue by jayakrishnang** [jayakrishnang/auction-manager-v2#10]

**Comment by anoobbava** [comment]
I will do that.

**Comment by jayakrishnang** [comment]
This is done @anoobbava

**Comment by anoobbava** [comment]
I was working on that issue, and got stuck with redis execution
anoobbava@anoobbava:~/ror/auction-manager-v2$ redis

Command 'redis' not found, did you mean:

  command 'pedis' from deb pev
  command 'redir' from deb redir

Try: sudo apt install <deb name>
